<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <UseWindowsForms>true</UseWindowsForms>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <PublishReadyToRun>true</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FontStashSharp.MonoGame" Version="1.5.3" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.2" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.CpuMath" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.DataView" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.TensorFlow" Version="5.0.0" />
    <PackageReference Include="Microsoft.NETCore.DotNetAppHost" Version="10.0.2" />
    <PackageReference Include="Microsoft.NETCore.DotNetHostPolicy" Version="8.0.23" />
    <PackageReference Include="Microsoft.NETCore.DotNetHostResolver" Version="8.0.23" />
    <PackageReference Include="Microsoft.NETCore.Jit" Version="2.0.8" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
    <PackageReference Include="Microsoft.NETCore.Targets" Version="5.0.0" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4.1" />
    <!-- <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4.1" /> -->
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4.1" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="runtime.native.System" Version="4.3.1" />
    <PackageReference Include="SciSharp.TensorFlow.Redist" Version="2.16.0" />
    <PackageReference Include="System.Collections" Version="4.3.0" />
    <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="10.0.2" />
    <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
    <PackageReference Include="System.Globalization" Version="4.3.0" />
    <PackageReference Include="System.IO" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Linq" Version="4.3.0" />
    <PackageReference Include="System.Runtime" Version="4.3.1" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
    <PackageReference Include="System.Runtime.Numerics" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
    <PackageReference Include="System.Text.Encoding" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Content\bin\Windows\" />
    <Folder Include="Content\FONTS\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Content\FONTS\FONT_A.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\FONTS\FONT_C.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\FONTS\FONT_DEF.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\FONTS\FONT_DEF_B.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\FONTS\FONT_E.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\FONTS\FONT_M.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Content\FONTS\FONT_TE.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="NN\discardingAI\fingerprint.pb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\discardingAI\saved_model.pb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\discardingAI\variables\variables.data-00000-of-00001">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\discardingAI\variables\variables.index">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\shoppingAI\fingerprint.pb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\shoppingAI\saved_model.pb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\shoppingAI\variables\variables.data-00000-of-00001">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\shoppingAI\variables\variables.index">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\strategyAI\fingerprint.pb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\strategyAI\saved_model.pb">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\strategyAI\variables\variables.data-00000-of-00001">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NN\strategyAI\variables\variables.index">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="RestoreDotnetTools" BeforeTargets="Restore">
    <Message Text="Restoring dotnet tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
</Project>